version: '3'
services:
  app-codeigniter3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - '8083:80'
    depends_on:
      - mysql
    restart: always
  mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=dbapp
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
